# Generated by Django 5.2 on 2025-04-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_empleados', '0002_empleado_groups_empleado_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
    ]
