# Generated by Django 5.2 on 2025-04-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_ordenes', '0002_alter_orden_usuario'),
        ('a_sucursales', '0001_initial'),
        ('a_usuarios', '0005_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_usuarios.direccionenvio'),
        ),
        migrations.AddField(
            model_name='orden',
            name='sucursal_retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_sucursales.sucursal'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_envio',
            field=models.CharField(choices=[('envio', 'Envío a domicilio'), ('recoger', 'Recoger en sucursal')], max_length=50),
        ),
    ]
