# Generated by Django 5.2 on 2025-04-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_usuarios', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
